default: &default
  adapter: postgresql
  encoding: unicode
  host:     <%= ENV['IP'] %>
  username: shine
  password: shine
  pool: 5

development:
  <<: *default
  database: shine_development

test:
  <<: *default
  database: shine_test
