# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f20575540f042e2572bed73dccf4ce9a683bc8c65965f42975274e52a98ca6262ff28f8624a91b7f6988ce298f2df8e7f75af235c62ea7a4e00b779addda7606

test:
  secret_key_base: a59ddedc47a53237dc8617c9e7782637f5e1658cefa272ec6aae196978fa971088b322e3a7b1bbefdaca6ec46dc01eb2f36ed6eacd703f44bd7db29df08f49b9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
